#!/usr/bin/env ruby
################################################################################
#  Copyright 2007-2008 Codehaus Foundation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'  

include RenderHelper

top_report_type_key = 'TOPVHOSTS'

top_report_type = TopReportType.find_by_key(top_report_type_key)
if not top_report_type
  top_report_type = TopReportType.new
  top_report_type.key = top_report_type_key
  top_report_type.title = 'Top VHosts'
  top_report_type.description = ''
  top_report_type.save!
end


sql = <<EOF
SELECT 
	PT.VHOST_ID,
	SUM(RESPONSE_TIME) AS RESPONSE_TIME,
	SUM(RESPONSE_TIME_SQUARE) AS RESPONSE_TIME_SQUARE,
	SUM(RESPONSE_BYTES) AS RESPONSE_BYTES,
	SUM(RESPONSE_BYTES_SQUARE) AS RESPONSE_BYTES_SQUARE
FROM PATH_TOTALS PT, PERIODS P
WHERE
	PT.PERIOD_ID = P.ID
	AND P.START > NOW() - INTERVAL '1 WEEK'
GROUP BY
	PT.VHOST_ID
ORDER BY SUM(RESPONSE_BYTES) DESC
LIMIT 10
EOF

records = PathTotal.find_by_sql(sql)

TopReport.transaction {
  TopReport.delete_all("top_report_type_id = '#{top_report_type.id}'")

  sort = 0
  for record in records
    sort = sort + 1
    rpt = TopReport.new
    rpt.top_report_type = top_report_type
    rpt.sort = sort
    rpt.title = record.vhost.host
    rpt.description = render_bytes(record.response_bytes)
    rpt.url = "/vhosts/#{record.vhost.host}"
    rpt.save!
  end
}