#!/usr/bin/env ruby
################################################################################
#  Copyright 2007-2008 Codehaus Foundation
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
################################################################################
require File.dirname(__FILE__) + '/../config/boot'
require RAILS_ROOT + '/config/environment'  

if RAILS_ENV != 'development'
  raise Exception.new('Can only purge development')
end


def truncate(table)
  puts "Truncating #{table}"
  ActiveRecord::Base.connection.execute("TRUNCATE TABLE #{table} CASCADE")
end

truncate('path_totals')
truncate('source_periods')
truncate('sources')
truncate('paths')
truncate('vhosts')
truncate('periods')
truncate('raw_lines')
truncate('rejected_lines')


v = Vhost.new
v.host = 'dist.codehaus.org'
v.aggregate_paths = true
v.save!